PREFIX = 'DLG+'
RESET = 'RESET'
GET_FW_REV = 'GETFWVERSION'
ERASE_IMAGE = 'IMGERASEALL'
BLOCK_UPDATE = 'IMGBLOCKUPDATE'
VERIFY_IMAGE = "IMGCHECK"
SCAN = "GAPSCAN"
CONNECT = "GAPCONNECT"
DISCONNECT = "GAPDISC"
GATT_BROWSE = "GATTBROWSE"
SUOTA_START = "SUOTASTART"
GATT_READ = "GATTREAD"
GATT_WRITE = "GATTWRITE"
GATT_WRITE_NO_RSP = "GATTWRITENORESP"

SCAN_ADDR_SUB = 'ADDR:'
SCAN_DATA_SUB = 'DATA:'
SCAN_RSSI_SUB = 'RSSI:'
SCAN_ADD_T_SUB = 'ADDR_TYPE:'
FW_SIZE_INFO = 'FW Image size:'

INIT_EVT = 'APP_INITIALIZED'
GET_VERSION_EVT = 'EVT_CLI_FW_VERSION'
CONNECTED_EVT = 'EVT_CONNECTED'
DISCONNECT_EVT = 'EVT_DISCONNECTED'
SCAN_COMPLETED = 'EVT_SCAN_COMPLETED'
BROWSE_COMPLETED = 'EVT_BROWSE_COMPLETED'
SUOTA_COMPLETE = 'EVT_SUOTA_TRANSFER_COMPLETE'
SUOTA_PROGRESS = 'EVT_SUOTA_SENT:'
SUOTA_READY = 'EVT_SUOTA_READY'
ADV_REPORT_EVT = 'EVT_ADV'
GATT_READ_EVT = "EVT_GATT_READ"
OK = 'OK'
END_IMAGE = "END IMAGE"


ADV_FILTER_KEY = 'filter-adv'
RSSI_FILTER_KEY = 'filter-rssi'
BD_ADDR_FILTER_KEY = 'filter-addr'
READ_CHARS_KEY = "chars-read"
WRITE_CHARS_KEY = "chars-write"
